#!/usr/bin/env bash
#configure nginx server to listen for port 80
cat > /etc/nginx/sites-enabled/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        return 200 "2";
        add_header Content-Type text/plain;
    }
}
EOF
