#!/usr/bin/env bash
# Run nginx as nginx

sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/80/g' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
